### ISSUE TITLE
running experiment error

### ISSUE THREAD

**Issue by phanxuanphucnd** [qute012/Wav2Keyword#1]
I trying testing the training process, but have a bug. Please help me

~/Wav2Keyword main !666 ?30 ❯ python downstream_kws_benchmark.py ./models/wav2vec_small.pt ./data/commands_v02 ./models/model.pt                                   
Traceback (most recent call last):
  File "downstream_kws_benchmark.py", line 1, in <module>
    from fairseq import models
  File "/home/phucpx/Wav2Keyword/fairseq/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/home/phucpx/Wav2Keyword/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/apps/conda/phucpx/envs/aubbert/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/phucpx/Wav2Keyword/fairseq/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 14, in <module>
    LabelSmoothedCrossEntropyCriterion
  File "/home/phucpx/Wav2Keyword/fairseq/fairseq/registry.py", line 67, in register_x_cls
    "Cannot register duplicate {} ({})".format(registry_name, name)
ValueError: Cannot register duplicate criterion (latency_augmented_label_smoothed_cross_entropy)

**Comment by raikarsagar** [comment]
Any working solutions for this error?
-Sagar
